- name: helloworldtest
image: hw-appd:v3
imagePullPolicy: IfNotPresent
envFrom:
- configMapRef:
name: appdynamics-info
env:
- name: ACCOUNT_ACCESS_KEY
valueFrom:
secretKeyRef:
key: appd-key
name: appd-secret
- name: APPD_OPTS
value: " -Dappdynamics.agent.accountAccessKey=$(ACCOUNT_ACCESS_KEY)
-Dappdynamics.controller.hostName=$(CONTROLLER_HOST)
-Dappdynamics.controller.port=$(CONTROLLER_PORT)
-Dappdynamics.controller.ssl.enabled=$(CONTROLLER_SSL_ENABLED)
-Dappdynamics.agent.accountName=$(ACCOUNT_NAME)
-Dappdynamics.agent.applicationName=$(APPLICATION_NAME)
-Dappdynamics.agent.tierName=$(TIER_NAME)
-Dappdynamics.agent.reuse.nodeName=true
-Dappdynamics.agent.reuse.nodeName.prefix=$(TIER_NAME)
-javaagent:/opt/appd-agent/javaagent.jar "
